# Generated by Django 4.0.3 on 2022-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_time',
            field=models.TimeField(null=True),
        ),
    ]
