# Generated by Django 4.0.2 on 2022-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0004_remove_doctor_doctor_remove_patient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
