# Generated by Django 4.0.2 on 2022-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0005_patient_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email_id',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
