# Generated by Django 4.0.2 on 2022-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0006_alter_patient_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
